### ISSUE TITLE
Not compatible with my_user_management

### ISSUE THREAD

**Issue by alexanderberner** [codesource/typo3-cdsrc_baseurl#1]
It seems that user is not allowed to change his password.
https://github.com/koninklijke-collective/my_user_management/issues/41

**Comment by alexanderberner** [comment]
wrong repsitory linked from the extension page https://extensions.typo3.org/extension/cdsrc_bepwreset/

**Comment by codesource** [comment]
I will check that. 
I have corrected the link in TYPO3 repository.
